/**
 * Pre-optimises the workshop photo set into responsive AVIF/WebP/JPEG assets
 * plus tiny inline LQIP placeholders.
 *
 * Source photos live outside the repo (SRC below) and are the plate-masked set
 * produced by scripts/blur-plates.mjs — run that first. Re-run only when the
 * photo set changes:  node scripts/blur-plates.mjs && node scripts/optimize-images.mjs
 *
 * Output: public/img/<name>-<width>.{avif,webp,jpg} and lib/generated/media.ts
 */
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const SRC =
  process.env.PHOTO_SRC ||
  "C:/Users/UPEKSH~1/AppData/Local/Temp/claude/C--Upeksha-s-folder-test-projects-mallwarachchi-auto-works/6368d107-5ba6-486d-81a2-969b5882e577/scratchpad/photos/blurred";

const OUT = path.join(process.cwd(), "public", "img");
const GEN = path.join(process.cwd(), "lib", "generated");

/** name -> source file. Landscape 3:2 unless `ratio` says otherwise. */
const SET = [
  // The hero is art-directed rather than one crop stretched to fit: a wide
  // frame for landscape viewports and a tall one for phones, both cut from
  // the same 1600x1200 photo by hand so the mechanic and the lit engine bay
  // survive either shape. `region` is in source pixels, applied before resize.
  {
    name: "hero",
    file: "p20.jpg",
    ratio: 16 / 9,
    widths: [768, 1152, 1400],
    quality: 46,
    region: { left: 200, top: 90, width: 1400, height: 787 },
  },
  {
    // Narrower than 3:4 on purpose: a full-height phone hero is roughly 0.46
    // wide-to-tall, so anything squarer just gets its sides cropped off again
    // by object-fit. 0.6 keeps the mechanic, his hands and the lit bay.
    name: "hero-portrait",
    file: "p20.jpg",
    ratio: 0.6,
    widths: [480, 720, 900],
    quality: 46,
    region: { left: 200, top: 0, width: 720, height: 1200 },
  },
  { name: "master-at-work", file: "p17.jpg", ratio: 4 / 3, widths: [480, 800, 1200] },
  { name: "yard-wide", file: "p01.jpg", ratio: 2 / 1, widths: [640, 1280] },

  // service cards (4:3)
  { name: "svc-engine", file: "p24.jpg" },
  { name: "svc-cooling", file: "p09.jpg" },
  { name: "svc-brakes", file: "p12.jpg" },
  { name: "svc-transmission", file: "p02.jpg" },
  { name: "svc-suspension", file: "p10.jpg" },
  { name: "svc-fuel", file: "p35.jpg" },
  { name: "svc-electrical", file: "p26.jpg" },
  { name: "svc-service", file: "p19.jpg" },

  // gallery
  { name: "g-01", file: "p05.jpg" },
  { name: "g-02", file: "p03.jpg" },
  { name: "g-03", file: "p02.jpg" },
  { name: "g-04", file: "p04.jpg" },
  { name: "g-05", file: "p10.jpg" },
  { name: "g-06", file: "p20.jpg" },
  { name: "g-07", file: "p13.jpg" },
  { name: "g-08", file: "p24.jpg" },
  { name: "g-09", file: "p26.jpg" },
  { name: "g-10", file: "p31.jpg" },
  { name: "g-11", file: "p35.jpg" },
  { name: "g-12", file: "p18.jpg" },
  { name: "g-13", file: "p29.jpg" },
  { name: "g-14", file: "p32.jpg" },
  { name: "g-15", file: "p03.jpg" },
  // g-16 (p16.jpg) dropped — outbuilding wall, not workshop work.
  { name: "g-17", file: "p37.jpg" },
  { name: "g-18", file: "p12.jpg" },
];

const DEFAULT_WIDTHS = [400, 700, 1100];
const DEFAULT_RATIO = 4 / 3;

fs.mkdirSync(OUT, { recursive: true });
fs.mkdirSync(GEN, { recursive: true });

const manifest = {};

for (const item of SET) {
  const src = path.join(SRC, item.file);
  if (!fs.existsSync(src)) {
    console.warn(`! missing source: ${src}`);
    continue;
  }
  const ratio = item.ratio ?? DEFAULT_RATIO;
  const widths = item.widths ?? DEFAULT_WIDTHS;
  const largest = widths[widths.length - 1];

  // A hand-picked region beats `position: "attention"`, which optimises for
  // edge energy and happily crops a face out of frame.
  const cut = () => {
    const pipe = sharp(src).rotate();
    return item.region ? pipe.extract(item.region) : pipe;
  };
  const fit = item.region
    ? { fit: "cover" }
    : { fit: "cover", position: "attention" };

  for (const w of widths) {
    const h = Math.round(w / ratio);
    const base = cut().resize(w, h, fit);
    await base.clone().avif({ quality: item.quality ?? 48, effort: 7 }).toFile(path.join(OUT, `${item.name}-${w}.avif`));
    await base.clone().webp({ quality: item.quality ? item.quality + 20 : 74 }).toFile(path.join(OUT, `${item.name}-${w}.webp`));
    await base
      .clone()
      .jpeg({ quality: 76, mozjpeg: true, progressive: true })
      .toFile(path.join(OUT, `${item.name}-${w}.jpg`));
  }

  // 20px-wide blurred placeholder, inlined as a data URI
  const lqip = await cut()
    .resize(20, Math.max(1, Math.round(20 / ratio)), fit)
    .blur(1.2)
    .webp({ quality: 30 })
    .toBuffer();

  manifest[item.name] = {
    widths,
    ratio: Number(ratio.toFixed(4)),
    width: largest,
    height: Math.round(largest / ratio),
    lqip: `data:image/webp;base64,${lqip.toString("base64")}`,
  };
  console.log(`✓ ${item.name}  ${widths.join("/")}`);
}

const ts = `// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export type MediaEntry = {
  widths: number[];
  ratio: number;
  width: number;
  height: number;
  lqip: string;
};

export const media = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, MediaEntry>;

export type MediaName = keyof typeof media;
`;
fs.writeFileSync(path.join(GEN, "media.ts"), ts, "utf8");
console.log(`\nWrote lib/generated/media.ts (${Object.keys(manifest).length} images)`);
